name: Construire APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Télécharger le projet
        uses: actions/checkout@v4

      - name: Installer les dépendances système
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            git zip unzip \
            openjdk-17-jdk \
            python3-pip \
            autoconf \
            libtool \
            pkg-config \
            zlib1g-dev \
            libncurses5-dev \
            libncursesw5-dev \
            cmake \
            libffi-dev \
            libssl-dev

      - name: Installer Buildozer
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install buildozer cython==0.29.36      - name: Configurer Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Installer Android SDK
        uses: android-actions/setup-android@v3

      - name: Installer les outils Android
        run: |
          sdkmanager "platform-tools" "platforms;android-35" "build-tools;35.0.0"
          yes | sdkmanager --licenses || true

      - name: Construire APK
        run: |
          buildozer android debug

      - name: Publier APK
        uses: actions/upload-artifact@v4
        with:
          name: calculatrice-pro
          path: bin/*.apk
